server:
  # 程序运行端口
  port: 15005

spring:
  mail:
    default-encoding: UTF-8
    # 邮箱类型
    host: ${HOST:smtp.qq.com}
    # 发送者邮箱地址
    username: ${USERNAME:xxx@xxx.com}
    # 授权码
    password: ${PASSWORD:xxxxxxxx}
    # 发送者昵称
    nickname: ${NICKNAME:nickname}
    # html模板文件目录
    template-dir: ${TEMP;ATE_DIR:message.ftl}
    # smtp端口
    port: 25