server:
  # 程序运行端口
  port: 15005

spring:
  mail:
    default-encoding: UTF-8
    # 邮箱类型
    host: ${MAIL_HOST:smtp.126.com}
    # 发送者邮箱地址
    username: ${MAIL_USERNAME:xxx@126.com}
    # 授权码
    password: ${MAIL_PASSWORD:XXXXXX}
    # 发送者昵称
    nickname: ${MAIL_NICKNAME:nickname}
    # html模板文件目录
    template-dir: ${MAIL_TEMPLATE_DIR:message.ftl}
    # smtp端口
    port: 25
